# Generated by Django 5.0.4 on 2024-05-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'Question Bank', 'verbose_name_plural': 'Question Banks'},
        ),
    ]
