# Generated by Django 5.0.4 on 2024-06-14 19:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'Question Bank', 'verbose_name_plural': 'Question Banks'},
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='explanation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='option1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='option2',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='option3',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='option4',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='option5',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionmcq',
            name='question_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='stem',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
