# Generated by Django 5.0.4 on 2024-05-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_failed_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Enroll', 'verbose_name_plural': 'Student Enrolls'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
