DIST_DHAKA = "dhaka"
DIST_CHATTAGRAM = "chattogram"
DIST_RAJSHAHI = "rajshahi"
DIST_KHULNA = "khulna"
DIST_BARISHAL = "barishal"
DIST_SYLHET = "sylhet"
DIST_RANGPUR = "rangpur"
DIST_MYMENSINGH = "mymensingh"
DIST_JASHORE = "jashore"
DIST_CUMILLA = "cumilla"
DIST_NOAKHALI = "noakhali"
DIST_FENI = "feni"
DIST_NARAYANGANJ = "narayanganj"
DIST_GAZIPUR = "gazipur"
DIST_BOGURA = "bogura"
DIST_KISHOREGANJ = "kishoreganj"
DIST_KUSHTIA = "kushtia"
DIST_JAMALPUR = "jamalpur"
DIST_TANGAIL = "tangail"
DIST_MOULVIBAZAR = "moulvibazar"
DIST_CHANDPUR = "chandpur"
DIST_JHENNAIDAH = "jhenaidah"
DIST_COXSBARZAR = "cox's bazar"
DIST_PABNA = "pabna"
DIST_NARSINGDI = "narsingdi"
DIST_SIRAJGANJ = "sirajganj"
DIST_NAOGAON = "naogaon"
DIST_MAGURA = "magura"
DIST_NILPHAMARI = "nilphamari"
DIST_BAGERHAT = "bagerhat"
DIST_BARGUNA = "barguna"
DIST_PANCHAGARH = "panchagarh"
DIST_THAKURGAON = "thakurgaon"
DIST_SATKHIRA = "satkhira"
DIST_FARIDPUR = "faridpur"
DIST_JOYPURHAT = "joypurhat"
DIST_GAIBANDHA = "gaibandha"
DIST_CHAPAINAWABGANJ = "chapainawabganj"
DIST_SHERPUR = "sherpur"
DIST_MADARIPUR = "madaripur"
DIST_HABIGANJ = "habiganj"
DIST_RANGAMATI = "rangamati"
DIST_NARAIL = "narail"
DIST_LAKSHMIPUR = "lakshmipur"
DIST_CHUADANGA = "chuadanga"
DIST_KURIGRAM = "kurigram"
DIST_MUNSHIGANJ = "munshiganj"
DIST_NETROKONA = "netrokona"
DIST_MEHERPUR = "meherpur"
DIST_NARSHINGDI = "narshingdi"
DIST_SHARIATPUR = "shariatpur"
DIST_SUNAMGANJ = "sunamganj"
DIST_BANDARBAN = "bandarban"
DIST_NATORE = "natore"
DIST_BRAHMANBARIA = "brahmanbaria"
DIST_PIROJPUR = "pirojpur"
DIST_JHALOKATI = "jhalokati"
DIST_JHENAIDAH = "jhenaidah"
DIST_GOPALGANJ = "gopalganj"
DIST_LALMONIRHAT = "lalmonirhat"
DIST_KHAGRACHHARI = "khagrachhari"

DISTRICT_CHOICES = [
    (DIST_DHAKA, DIST_DHAKA),
    (DIST_CHATTAGRAM, DIST_CHATTAGRAM),
    (DIST_RAJSHAHI, DIST_RAJSHAHI),
    (DIST_KHULNA, DIST_KHULNA),
    (DIST_BARISHAL, DIST_BARISHAL),
    (DIST_SYLHET, DIST_SYLHET),
    (DIST_RANGPUR, DIST_RANGPUR),
    (DIST_MYMENSINGH, DIST_MYMENSINGH),
    (DIST_JASHORE, DIST_JASHORE),
    (DIST_CUMILLA, DIST_CUMILLA),
    (DIST_NOAKHALI, DIST_NOAKHALI),
    (DIST_FENI, DIST_FENI),
    (DIST_NARAYANGANJ, DIST_NARAYANGANJ),
    (DIST_GAZIPUR, DIST_GAZIPUR),
    (DIST_BOGURA, DIST_BOGURA),
    (DIST_KISHOREGANJ, DIST_KISHOREGANJ),
    (DIST_KUSHTIA, DIST_KUSHTIA),
    (DIST_JAMALPUR, DIST_JAMALPUR),
    (DIST_TANGAIL, DIST_TANGAIL),
    (DIST_MOULVIBAZAR, DIST_MOULVIBAZAR),
    (DIST_CHANDPUR, DIST_CHANDPUR),
    (DIST_JHENNAIDAH, DIST_JHENNAIDAH),
    (DIST_COXSBARZAR, DIST_COXSBARZAR),
    (DIST_PABNA, DIST_PABNA),
    (DIST_NARSINGDI, DIST_NARSINGDI),
    (DIST_SIRAJGANJ, DIST_SIRAJGANJ),
    (DIST_NAOGAON, DIST_NAOGAON),
    (DIST_MAGURA, DIST_MAGURA),
    (DIST_NILPHAMARI, DIST_NILPHAMARI),
    (DIST_BAGERHAT, DIST_BAGERHAT),
    (DIST_BARGUNA, DIST_BARGUNA),
    (DIST_PANCHAGARH, DIST_PANCHAGARH),
    (DIST_THAKURGAON, DIST_THAKURGAON),
    (DIST_SATKHIRA, DIST_SATKHIRA),
    (DIST_FARIDPUR, DIST_FARIDPUR),
    (DIST_JOYPURHAT, DIST_JOYPURHAT),
    (DIST_GAIBANDHA, DIST_GAIBANDHA),
    (DIST_CHAPAINAWABGANJ, DIST_CHAPAINAWABGANJ),
    (DIST_SHERPUR, DIST_SHERPUR),
    (DIST_MADARIPUR, DIST_MADARIPUR),
    (DIST_HABIGANJ, DIST_HABIGANJ),
    (DIST_RANGAMATI, DIST_RANGAMATI),
    (DIST_NARAIL, DIST_NARAIL),
    (DIST_LAKSHMIPUR, DIST_LAKSHMIPUR),
    (DIST_CHUADANGA, DIST_CHUADANGA),
    (DIST_KURIGRAM, DIST_KURIGRAM),
    (DIST_MUNSHIGANJ, DIST_MUNSHIGANJ),
    (DIST_NETROKONA, DIST_NETROKONA),
    (DIST_MEHERPUR, DIST_MEHERPUR),
    (DIST_NARSHINGDI, DIST_NARSHINGDI),
    (DIST_SHARIATPUR, DIST_SHARIATPUR),
    (DIST_SUNAMGANJ, DIST_SUNAMGANJ),
    (DIST_BANDARBAN, DIST_BANDARBAN),
    (DIST_NATORE, DIST_NATORE),
    (DIST_BRAHMANBARIA, DIST_BRAHMANBARIA),
    (DIST_PIROJPUR, DIST_PIROJPUR),
    (DIST_JHALOKATI, DIST_JHALOKATI),
    (DIST_GOPALGANJ, DIST_GOPALGANJ),
    (DIST_LALMONIRHAT, DIST_LALMONIRHAT),
    (DIST_KHAGRACHHARI, DIST_KHAGRACHHARI),
    (DIST_JHENAIDAH, DIST_JHENAIDAH),
]
