# Generated by Django 5.0.3 on 2024-04-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
