# Generated by Django 5.0.3 on 2024-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
