# Generated by Django 5.0.3 on 2024-03-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_and_street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('sub_district', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(choices=[('dhaka', 'dhaka'), ('chattogram', 'chattogram'), ('rajshahi', 'rajshahi'), ('khulna', 'khulna'), ('barishal', 'barishal'), ('sylhet', 'sylhet'), ('rangpur', 'rangpur'), ('mymensingh', 'mymensingh'), ('jashore', 'jashore'), ('cumilla', 'cumilla'), ('noakhali', 'noakhali'), ('feni', 'feni'), ('narayanganj', 'narayanganj'), ('gazipur', 'gazipur'), ('bogura', 'bogura'), ('kishoreganj', 'kishoreganj'), ('kushtia', 'kushtia'), ('jamalpur', 'jamalpur'), ('tangail', 'tangail'), ('moulvibazar', 'moulvibazar'), ('chandpur', 'chandpur'), ('jhenaidah', 'jhenaidah'), ("cox's bazar", "cox's bazar"), ('pabna', 'pabna'), ('narsingdi', 'narsingdi'), ('sirajganj', 'sirajganj'), ('naogaon', 'naogaon'), ('magura', 'magura'), ('nilphamari', 'nilphamari'), ('bagerhat', 'bagerhat'), ('barguna', 'barguna'), ('panchagarh', 'panchagarh'), ('thakurgaon', 'thakurgaon'), ('satkhira', 'satkhira'), ('faridpur', 'faridpur'), ('joypurhat', 'joypurhat'), ('gaibandha', 'gaibandha'), ('chapainawabganj', 'chapainawabganj'), ('sherpur', 'sherpur'), ('madaripur', 'madaripur'), ('habiganj', 'habiganj'), ('rangamati', 'rangamati'), ('narail', 'narail'), ('lakshmipur', 'lakshmipur'), ('chuadanga', 'chuadanga'), ('kurigram', 'kurigram'), ('munshiganj', 'munshiganj'), ('netrokona', 'netrokona'), ('meherpur', 'meherpur'), ('narshingdi', 'narshingdi'), ('shariatpur', 'shariatpur'), ('sunamganj', 'sunamganj'), ('bandarban', 'bandarban'), ('natore', 'natore'), ('brahmanbaria', 'brahmanbaria'), ('pirojpur', 'pirojpur'), ('jhalokati', 'jhalokati'), ('gopalganj', 'gopalganj'), ('lalmonirhat', 'lalmonirhat'), ('khagrachhari', 'khagrachhari'), ('jhenaidah', 'jhenaidah')], default='dhaka', max_length=255)),
                ('country', models.CharField(default='Bangladesh', max_length=255)),
            ],
        ),
    ]
