BASE_DIR = "D:/personal/django_rf_university_api"  # this var is for test purpose

ROLE_ADMIN = "admin"
ROLE_STAFF = "staff"
ROLE_STUDENT = "student"
ROLE_USER = "user"

USER_ROLE_CHOICES = [
    (ROLE_ADMIN, ROLE_ADMIN),
    (ROLE_STAFF, ROLE_STAFF),
    (ROLE_STUDENT, ROLE_STUDENT),
    (ROLE_USER, ROLE_USER),
]

DES_DEAN = "dean"
DES_CHAIRMAN = "chairman"
DES_PROFESSOR = "professor"
DES_ASSOCIATE_PROFESSOR = "associate_professor"

DESIGNATION_ROLE_CHOICES = [
    (DES_DEAN, DES_DEAN),
    (DES_CHAIRMAN, DES_CHAIRMAN),
    (DES_PROFESSOR, DES_PROFESSOR),
    (DES_ASSOCIATE_PROFESSOR, DES_ASSOCIATE_PROFESSOR),
]

DEF_FISH = "fisheries"
DEF_MARINE = "marine"
DEF_OCEAN = "oceanography"

DEPARTMENT_CHOICES = [
    (DEF_FISH, DEF_FISH),
    (DEF_MARINE, DEF_MARINE),
    (DEF_OCEAN, DEF_OCEAN),
]

YEAR_1ST = "1st year"
YEAR_2ND = "2nd year"
YEAR_3RD = "3rd year"
YEAR_4TH = "4th year"

YEAR_CHOICES = [
    (YEAR_1ST, YEAR_1ST),
    (YEAR_2ND, YEAR_2ND),
    (YEAR_3RD, YEAR_3RD),
    (YEAR_4TH, YEAR_4TH),
]

DEGREE_BSC = "B.Sc"
DEGREE_MSC = "M.Sc"
DEGREE_PHD = "PhD"

DEGREE_CHOICES = [
    (DEGREE_BSC, DEGREE_BSC),
    (DEGREE_MSC, DEGREE_MSC),
    (DEGREE_PHD, DEGREE_PHD),
]

GENDER_MALE = "male"
GENDER_FEMALE = "female"
GENDER_OTHER = "other"

GENDER_CHOICES = [
    (GENDER_MALE, GENDER_MALE),
    (GENDER_FEMALE, GENDER_FEMALE),
    (GENDER_OTHER, GENDER_OTHER),
]
