ROLE_ADMIN = "admin"
ROLE_STAFF = "staff"
ROLE_STUDENT = "student"
ROLE_USER = "user"

USER_ROLE_CHOICES = [
    (ROLE_ADMIN, ROLE_ADMIN),
    (ROLE_STAFF, ROLE_STAFF),
    (ROLE_STUDENT, ROLE_STUDENT),
    (ROLE_USER, ROLE_USER),
]

DESIGNATION_DEAN = "dean"
DESIGNATION_CHAIRMAN = "chairman"
DESIGNATION_PROFESSOR = "professor"
DESIGNATION_ASSOCIATE_PROFESSOR = "associate_professor"

DESIGNATION_ROLE_CHOICES = [
    (DESIGNATION_DEAN, DESIGNATION_DEAN),
    (DESIGNATION_CHAIRMAN, DESIGNATION_CHAIRMAN),
    (DESIGNATION_PROFESSOR, DESIGNATION_PROFESSOR),
    (DESIGNATION_ASSOCIATE_PROFESSOR, DESIGNATION_ASSOCIATE_PROFESSOR),
]

DEPT_FISH = "fisheries"
DEPT_MARINE = "marine"
DEPT_OCEAN = "oceanography"

DEPARTMENT_CHOICES = [
    (DEPT_FISH, DEPT_FISH),
    (DEPT_MARINE, DEPT_MARINE),
    (DEPT_OCEAN, DEPT_OCEAN),
]

YEAR_1ST = "1st year"
YEAR_2ND = "2nd year"
YEAR_3RD = "3rd year"
YEAR_4TH = "4th year"

YEAR_CHOICES = [
    (YEAR_1ST, YEAR_1ST),
    (YEAR_2ND, YEAR_2ND),
    (YEAR_3RD, YEAR_3RD),
    (YEAR_4TH, YEAR_4TH),
]

DEGREE_BSC = "B.Sc"
DEGREE_MSC = "M.Sc"
DEGREE_PHD = "PhD"

DEGREE_CHOICES = [
    (DEGREE_BSC, DEGREE_BSC),
    (DEGREE_MSC, DEGREE_MSC),
    (DEGREE_PHD, DEGREE_PHD),
]

GENDER_MALE = "male"
GENDER_FEMALE = "female"
GENDER_OTHER = "other"

GENDER_CHOICES = [
    (GENDER_MALE, GENDER_MALE),
    (GENDER_FEMALE, GENDER_FEMALE),
    (GENDER_OTHER, GENDER_OTHER),
]
